# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-26 04:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imager_images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default=b'Seattle', max_length=25)),
                ('state', models.CharField(default=b'WA', max_length=2)),
                ('pic', models.ImageField(upload_to=b'profile_pics', verbose_name=imager_images.models.ImagerPhoto)),
                ('camera_type', models.CharField(choices=[(b'CN', b'Canon'), (b'NK', b'Nikon'), (b'KD', b'Kodak'), (b'SN', b'Sony'), (b'IP', b'iPhone')], max_length=2)),
                ('photo_style', models.CharField(choices=[(b'CR', b'Color'), (b'BW', b'Black and White'), (b'LS', b'Landscape'), (b'PR', b'Portrait'), (b'MI', b'Micro'), (b'MA', b'Macro')], default=b'CR', max_length=2)),
                ('job', models.CharField(default=b'', max_length=75)),
                ('website', models.URLField(default=b'', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
