# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-16 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='city',
            field=models.CharField(default='Seattle', max_length=25),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='state',
            field=models.CharField(default='WA', max_length=2),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='website',
            field=models.URLField(default='', max_length=255),
        ),
    ]
