# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-19 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagerprofile',
            old_name='photography_style',
            new_name='photo_style',
        ),
    ]
