# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-19 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='photography_style',
            field=models.CharField(choices=[('CR', 'Color'), ('BW', 'Black and White'), ('LS', 'Landscape'), ('PR', 'Portrait'), ('MI', 'Micro'), ('MA', 'Macro')], default='CR', max_length=2),
        ),
    ]
