# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import imager_images.models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0002_auto_20170621_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagerprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='imagerprofile',
            name='pic',
            field=models.ImageField(default='static/default_pic.jpg', upload_to='', verbose_name=imager_images.models.ImagerPhoto),
        ),
        migrations.AddField(
            model_name='imagerprofile',
            name='state',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='city',
            field=models.CharField(default='', max_length=25),
        ),
    ]
