# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-19 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0002_auto_20170719_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='photo_style',
            field=models.CharField(choices=[('Color', 'CR'), ('Black and White', 'BW'), ('LS', 'Landscape'), ('PR', 'Portrait'), ('MI', 'Micro'), ('MA', 'Macro')], default='CR', max_length=2),
        ),
    ]
