# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-19 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0004_auto_20170719_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='photo_style',
            field=models.CharField(choices=[('CR', 'Color'), ('BW', 'Black and White'), ('LS', 'Landscape'), ('PR', 'Portrait'), ('MI', 'Micro'), ('MA', 'Macro')], default='Color', max_length=25),
        ),
    ]
