# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import imager_images.models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0004_auto_20170626_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='pic',
            field=models.ImageField(default='../static/default_pic.jpg', upload_to='', verbose_name=imager_images.models.ImagerPhoto),
        ),
    ]
