# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import imager_images.models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0005_auto_20170626_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='pic',
            field=models.ImageField(default='', upload_to='profile_pics', verbose_name=imager_images.models.ImagerPhoto),
        ),
    ]
