language: python
python:
  - "2.7"
  - "3.6"

env:
  - SECRET_KEY='potato' DATABASE_NAME='usersdb' DATABASE_USER='' DATABASE_HOST="127.0.0.1" DATABASE_PASSWORD=''

# command to install dependencies
install:
  - pip install -U pip
  - pip install -r requirements.pip
  - pip install coverage
  - pip install coveralls
  - pip install python-coveralls

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE test_db5;" -U postgres
  - psql -c "CREATE DATABASE usersdb;" -U postgres

# command to run tests
script:
  - python imagersite/manage.py migrate
  - coverage run imagersite/manage.py test imagersite

after_success:
  - coveralls

notifications:
email: false
