# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-17 03:13
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerphoto',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(upload_to='images'),
        ),
    ]
