# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 18:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imager_images', '0002_auto_20170626_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagerAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('published', models.CharField(choices=[('PB', 'public'), ('PV', 'private'), ('SH', 'shared')], default='PV', max_length=2)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='imagerphoto',
            old_name='date',
            new_name='date_uploaded',
        ),
        migrations.AddField(
            model_name='imagerphoto',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='imagerphoto',
            name='date_published',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagerphoto',
            name='published',
            field=models.CharField(choices=[('PB', 'public'), ('PV', 'private'), ('SH', 'shared')], default='PV', max_length=2),
        ),
        migrations.AddField(
            model_name='imagerphoto',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='imageralbum',
            name='cover',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='imager_images.ImagerPhoto'),
        ),
        migrations.AddField(
            model_name='imageralbum',
            name='photo',
            field=models.ManyToManyField(default='', null=True, related_name='albums', to='imager_images.ImagerPhoto'),
        ),
        migrations.AddField(
            model_name='imageralbum',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL),
        ),
    ]
