# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0003_auto_20170626_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageralbum',
            name='photo',
        ),
        migrations.AddField(
            model_name='imageralbum',
            name='photos',
            field=models.ManyToManyField(default='', related_name='albums', to='imager_images.ImagerPhoto'),
        ),
    ]
