# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-17 03:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0004_auto_20170626_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageralbum',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='imager_images.ImagerPhoto'),
        ),
        migrations.AlterField(
            model_name='imageralbum',
            name='photos',
            field=models.ManyToManyField(blank=True, default='', related_name='albums', to='imager_images.ImagerPhoto'),
        ),
        migrations.AlterField(
            model_name='imagerphoto',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(upload_to='images'),
        ),
    ]
