# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0004_auto_20170626_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageralbum',
            old_name='photos',
            new_name='photo',
        ),
    ]
