# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 23:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0005_auto_20170713_2110'),
        ('imager_images', '0005_auto_20170706_2256'),
    ]

    operations = [
    ]
